version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db/:/docker-entrypoint-initdb.d/ 
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: ./app
    depends_on:
      - db
    volumes:
      - ./app:/app 
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db_data:

networks:
  app-network:
